task: exams
dataset_path: eci-io/climate-evalutaion
dataset_name: null # translated_exams
dataset_kwargs: 
  data_files:
    test: "exams/translated/test.csv"
output_type: multiple_choice
# training_split: train
# validation_split: validation
test_split: test
doc_to_text: question_stem
doc_to_target: "{{answer}}" #"{{choices.label.index(answerKey.lstrip())}}"
doc_to_choice: "{{choices.text}}"
should_decontaminate: true
process_docs: !function utils.process_docs
# doc_to_decontamination_query: question_stem
metric_list:
  - metric: acc
    aggregation: mean
    higher_is_better: true
  - metric: acc_norm
    aggregation: mean
    higher_is_better: true
